- id: '1618902213502'
  alias: Toggle Cloud Light
  description: ''
  trigger:
  - platform: webhook
    webhook_id: '100'
    allowed_methods:
    - POST
    - PUT
    local_only: true
  condition: []
  action:
  - type: toggle
    device_id: 62f13da49d37122422a99fd9a0672db8
    entity_id: switch.verisure_switch
    domain: switch
  mode: single
- id: '1624346947824'
  alias: Restore Samba Backup sensor on startup
  trigger:
  - event: start
    platform: homeassistant
  action:
  - service: hassio.addon_stdin
    data:
      addon: 15d21743_samba_backup
      input: restore-sensor
  mode: single
- id: '1674202038324'
  alias: Low battery level detection & notification for all battery sensors
  description: ''
  use_blueprint:
    path: sbyx/low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      actions:
      - service: notify.mobile_app_christians_iphone_2
        data:
          message: '{{sensors|replace(", ", "\n")}}'
          title: Low Battery Warning
      threshold: 10
      exclude:
        entity_id:
        - sensor.christians_iphone_2_battery_level
- id: '1679658995046'
  alias: Mount Synology
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: shell_command.mount_syn_folder
    data: {}
  mode: single
- id: '1701207225668'
  alias: Cloud Lightning
  description: ''
  trigger:
  - platform: webhook
    allowed_methods:
    - POST
    - PUT
    local_only: true
    webhook_id: storm
  condition: []
  action:
  - service: light.turn_on
    target:
      entity_id: []
      device_id:
      - f2253fe283ebeeb725aac76887945f22
      area_id: []
    data:
      effect: Lightning
      rgb_color:
      - 255
      - 255
      - 255
  mode: single
- id: '1701345981099'
  alias: Cloud Red
  description: ''
  trigger:
  - platform: webhook
    allowed_methods:
    - POST
    - PUT
    local_only: true
    webhook_id: cloud-red
  condition: []
  action:
  - service: light.turn_on
    target:
      entity_id: []
      device_id:
      - f2253fe283ebeeb725aac76887945f22
      area_id: []
    data:
      rgb_color:
      - 255
      - 0
      - 0
      effect: Solid
  mode: single
- id: '1701346249652'
  alias: Cloud Blue
  description: ''
  trigger:
  - platform: webhook
    allowed_methods:
    - POST
    - PUT
    local_only: true
    webhook_id: cloud-blue
  condition: []
  action:
  - service: light.turn_on
    target:
      entity_id: []
      device_id:
      - f2253fe283ebeeb725aac76887945f22
      area_id: []
    data:
      effect: Solid
      rgb_color:
      - 0
      - 76
      - 255
  mode: single
- id: '1701346601362'
  alias: Cloud White
  description: ''
  trigger:
  - platform: webhook
    allowed_methods:
    - POST
    - PUT
    local_only: true
    webhook_id: cloud-white
  condition: []
  action:
  - service: light.toggle
    target:
      entity_id: []
      device_id:
      - f2253fe283ebeeb725aac76887945f22
      area_id: []
    data:
      rgb_color:
      - 245
      - 245
      - 245
      effect: Solid
  mode: single
- id: '1707217786984'
  alias: Update notifications
  description: ''
  use_blueprint:
    path: mdegat01/update_notifications.yaml
    input:
      mobile_app_device: d6f5bb00c6bd80e6f8447e4fe02bf809
      update_entities:
      - update.home_assistant_core_update
      - update.home_assistant_operating_system_update
      - update.home_assistant_supervisor_update
      mobile_app_device_2: d6f5bb00c6bd80e6f8447e4fe02bf809
      run_config_check: true
- id: '1716884266375'
  alias: Doorbell Video Livingroom Nest
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_button.doorbell_virtual_button
  condition: []
  action:
  - service: camera.play_stream
    metadata: {}
    data:
      format: hls
      media_player: media_player.living_room_2
    target:
      entity_id: camera.aarlo_doorbell
  mode: single
- id: '1718956792328'
  alias: UPS Unavailable Notification
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.ups_battery_charge
    from:
    to: unavailable
    for:
      hours: 0
      minutes: 1
      seconds: 0
  condition: []
  action:
  - service: notify.mobile_app_christians_iphone_2
    data:
      message: "UPS Offline again \U0001FAAB"
      title: UPS Event
  mode: single
- id: '1718979526238'
  alias: UPS Online Notification
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.ups_status
    from: unavailable
    to:
    for:
      hours: 0
      minutes: 1
      seconds: 0
  condition: []
  action:
  - service: notify.mobile_app_christians_iphone_2
    data:
      message: "\U0001F50B UPS Online again "
      title: UPS Event
  mode: single
- id: '1732448687057'
  alias: Gym Lights On/Off
  description: ''
  triggers:
  - domain: mqtt
    device_id: e60364c49ac435b7501e1dedc3414580
    type: action
    subtype: toggle
    trigger: device
  conditions: []
  actions:
  - type: toggle
    device_id: 4704fdcff0f46becf4831e763fbb69bf
    entity_id: 793e539428dec2eeb57e0f6604e635f1
    domain: light
  mode: single
- id: '1732448894365'
  alias: Gym Brightness Up
  description: ''
  triggers:
  - domain: mqtt
    device_id: e60364c49ac435b7501e1dedc3414580
    type: action
    subtype: brightness_up_click
    trigger: device
  conditions: []
  actions:
  - device_id: 4704fdcff0f46becf4831e763fbb69bf
    domain: light
    entity_id: 793e539428dec2eeb57e0f6604e635f1
    type: brightness_increase
  mode: single
- id: '1732448942273'
  alias: Gym Brightness Down
  description: ''
  triggers:
  - domain: mqtt
    device_id: e60364c49ac435b7501e1dedc3414580
    type: action
    subtype: brightness_down_click
    trigger: device
  conditions: []
  actions:
  - device_id: 4704fdcff0f46becf4831e763fbb69bf
    domain: light
    entity_id: 793e539428dec2eeb57e0f6604e635f1
    type: brightness_decrease
  mode: single
- id: '1733397222540'
  alias: Varmekabler Bad >30
  description: ''
  triggers:
  - type: temperature
    device_id: 15becaa5f6aa157b626aa79bf994ac28
    entity_id: cca94149328324f7953823c061b8d75c
    domain: sensor
    trigger: device
    above: 30
    for:
      hours: 0
      minutes: 0
      seconds: 0
  conditions: []
  actions:
  - action: notify.notify
    metadata: {}
    data:
      message: Varmekabler bad >30
  mode: single
- id: '1733397276363'
  alias: Varmekabler bad <22
  description: ''
  triggers:
  - type: temperature
    device_id: 15becaa5f6aa157b626aa79bf994ac28
    entity_id: cca94149328324f7953823c061b8d75c
    domain: sensor
    trigger: device
    for:
      hours: 0
      minutes: 0
      seconds: 0
    below: 22
  conditions: []
  actions:
  - action: notify.notify
    metadata: {}
    data:
      message: Varmekabler bad <22
  mode: single
- id: '1735805481133'
  alias: Tag Test is scanned
  description: ''
  triggers:
  - trigger: tag
    tag_id: f4bb661b-0974-4cf9-afa9-11c1a5ac98a8
  conditions: []
  actions:
  - action: notify.notify
    metadata: {}
    data:
      message: Tag scanned
  mode: single
