- id: '1624346947824'
  alias: Restore Samba Backup sensor on startup
  triggers:
  - event: start
    trigger: homeassistant
  actions:
  - data:
      addon: 15d21743_samba_backup
      input: restore-sensor
    action: hassio.addon_stdin
  mode: single
- id: '1674202038324'
  alias: Low battery level detection & notification for all battery sensors
  description: ''
  use_blueprint:
    path: sbyx/low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      actions:
      - service: notify.mobile_app_christians_iphone_2
        data:
          message: '{{sensors|replace(", ", "\n")}}'
          title: Low Battery Warning
      threshold: 10
      exclude:
        entity_id:
        - sensor.christians_iphone_2_battery_level
- id: '1679658995046'
  alias: Mount Synology
  description: ''
  triggers:
  - event: start
    trigger: homeassistant
  conditions: []
  actions:
  - data: {}
    action: shell_command.mount_syn_folder
  mode: single
- id: '1701207225668'
  alias: Cloud Lightning
  description: ''
  triggers:
  - allowed_methods:
    - POST
    - PUT
    local_only: true
    webhook_id: storm
    trigger: webhook
  conditions: []
  actions:
  - target:
      entity_id: []
      device_id:
      - f2253fe283ebeeb725aac76887945f22
      area_id: []
    data:
      effect: Lightning
      rgb_color:
      - 255
      - 255
      - 255
    action: light.turn_on
  mode: single
- id: '1701345981099'
  alias: Cloud Red
  description: ''
  triggers:
  - allowed_methods:
    - POST
    - PUT
    local_only: true
    webhook_id: cloud-red
    trigger: webhook
  conditions: []
  actions:
  - target:
      entity_id: []
      device_id:
      - f2253fe283ebeeb725aac76887945f22
      area_id: []
    data:
      rgb_color:
      - 255
      - 0
      - 0
      effect: Solid
    action: light.turn_on
  mode: single
- id: '1701346249652'
  alias: Cloud Blue
  description: ''
  triggers:
  - allowed_methods:
    - POST
    - PUT
    local_only: true
    webhook_id: cloud-blue
    trigger: webhook
  conditions: []
  actions:
  - target:
      entity_id: []
      device_id:
      - f2253fe283ebeeb725aac76887945f22
      area_id: []
    data:
      effect: Solid
      rgb_color:
      - 0
      - 76
      - 255
    action: light.turn_on
  mode: single
- id: '1701346601362'
  alias: Cloud White
  description: ''
  triggers:
  - allowed_methods:
    - POST
    - PUT
    local_only: true
    webhook_id: cloud-white
    trigger: webhook
  conditions: []
  actions:
  - target:
      entity_id: []
      device_id:
      - f2253fe283ebeeb725aac76887945f22
      area_id: []
    data:
      rgb_color:
      - 245
      - 245
      - 245
      effect: Solid
    action: light.toggle
  mode: single
- id: '1707217786984'
  alias: Update notifications
  description: ''
  use_blueprint:
    path: mdegat01/update_notifications.yaml
    input:
      mobile_app_device: d6f5bb00c6bd80e6f8447e4fe02bf809
      update_entities:
      - update.home_assistant_core_update
      - update.home_assistant_operating_system_update
      - update.home_assistant_supervisor_update
      mobile_app_device_2: d6f5bb00c6bd80e6f8447e4fe02bf809
      run_config_check: true
- id: '1718956792328'
  alias: UPS Unavailable Notification
  description: ''
  triggers:
  - entity_id:
    - sensor.ups_battery_charge_2
    from:
    to: unavailable
    for:
      hours: 0
      minutes: 1
      seconds: 0
    trigger: state
  conditions: []
  actions:
  - data:
      message: "UPS Offline again \U0001FAAB"
      title: UPS Event
    action: notify.mobile_app_christians_iphone_2
  mode: single
- id: '1718979526238'
  alias: UPS Online Notification
  description: ''
  triggers:
  - entity_id:
    - sensor.ups_status_2
    from: unavailable
    to:
    for:
      hours: 0
      minutes: 1
      seconds: 0
    trigger: state
  conditions: []
  actions:
  - data:
      message: "\U0001F50B UPS Online again "
      title: UPS Event
    action: notify.mobile_app_christians_iphone_2
  mode: single
- id: '1732448687057'
  alias: Gym Lights On/Off
  description: ''
  triggers:
  - domain: mqtt
    device_id: e60364c49ac435b7501e1dedc3414580
    type: action
    subtype: toggle
    trigger: device
  conditions: []
  actions:
  - type: toggle
    device_id: 4704fdcff0f46becf4831e763fbb69bf
    entity_id: 793e539428dec2eeb57e0f6604e635f1
    domain: light
  mode: single
- id: '1732448894365'
  alias: Gym Brightness Up
  description: ''
  triggers:
  - domain: mqtt
    device_id: e60364c49ac435b7501e1dedc3414580
    type: action
    subtype: brightness_up_click
    trigger: device
  conditions: []
  actions:
  - device_id: 4704fdcff0f46becf4831e763fbb69bf
    domain: light
    entity_id: 793e539428dec2eeb57e0f6604e635f1
    type: brightness_increase
  mode: single
- id: '1732448942273'
  alias: Gym Brightness Down
  description: ''
  triggers:
  - domain: mqtt
    device_id: e60364c49ac435b7501e1dedc3414580
    type: action
    subtype: brightness_down_click
    trigger: device
  conditions: []
  actions:
  - device_id: 4704fdcff0f46becf4831e763fbb69bf
    domain: light
    entity_id: 793e539428dec2eeb57e0f6604e635f1
    type: brightness_decrease
  mode: single
- id: '1733397222540'
  alias: Varmekabler Bad >30
  description: ''
  triggers:
  - type: temperature
    device_id: 15becaa5f6aa157b626aa79bf994ac28
    entity_id: cca94149328324f7953823c061b8d75c
    domain: sensor
    trigger: device
    above: 30
    for:
      hours: 0
      minutes: 0
      seconds: 0
  conditions: []
  actions:
  - action: notify.notify
    metadata: {}
    data:
      message: Varmekabler bad >30
  mode: single
- id: '1733397276363'
  alias: Varmekabler bad <22
  description: ''
  triggers:
  - type: temperature
    device_id: 15becaa5f6aa157b626aa79bf994ac28
    entity_id: cca94149328324f7953823c061b8d75c
    domain: sensor
    trigger: device
    for:
      hours: 0
      minutes: 0
      seconds: 0
    below: 22
  conditions: []
  actions:
  - action: notify.notify
    metadata: {}
    data:
      message: Varmekabler bad <22
  mode: single
- id: '1735805481133'
  alias: Tag Test is scanned
  description: ''
  triggers:
  - trigger: tag
    tag_id: f4bb661b-0974-4cf9-afa9-11c1a5ac98a8
  conditions: []
  actions:
  - action: notify.notify
    metadata: {}
    data:
      message: Tag scanned
  mode: single
- id: '1741349261358'
  alias: Aqara Button 1 Office Lights
  description: ''
  triggers:
  - domain: mqtt
    device_id: 84fa896a2a4671844bab358bbc3df444
    type: action
    subtype: single
    trigger: device
    id: aqara-button-1-single
  - domain: mqtt
    device_id: 84fa896a2a4671844bab358bbc3df444
    type: action
    subtype: double
    trigger: device
    id: aqara-button-1-double
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - aqara-button-1-single
      sequence:
      - action: light.toggle
        metadata: {}
        data: {}
        target:
          entity_id:
          - light.left_elgato_key_light_air
          - light.right_elgato_keylight_air
      - choose: []
    - conditions:
      - condition: trigger
        id:
        - aqara-button-1-double
      sequence:
      - action: light.turn_on
        metadata: {}
        data:
          brightness_pct: 100
        target:
          area_id: 55918db61e274c7898dd524589cff500
        enabled: false
      - action: light.toggle
        metadata: {}
        data:
          color_name: azure
          effect: Chase Flash Rnd
          brightness_pct: 30
        target:
          device_id: f2253fe283ebeeb725aac76887945f22
  mode: single
- id: '1746096341274'
  alias: Cooktop on - Lights on
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - switch.cooktop_power
    from: 'off'
    to: 'on'
  conditions: []
  actions:
  - action: light.turn_on
    metadata: {}
    data: {}
    target:
      device_id:
      - c2df77741be7400dbd6e4483bdc60b57
      - 73a326af70cdcabb55111e83863debe8
  mode: single
- id: '1758441743922'
  alias: Turn off Away Mode if Door Unlocked
  description: ''
  triggers:
  - device_id: 9f62547d48e91fa861a2c4d191713a2f
    domain: lock
    entity_id: 863de24c46a11bfd6e38cba5f4f74897
    type: unlocked
    trigger: device
  conditions:
  - condition: state
    entity_id: input_boolean.away_mode
    state: 'on'
  actions:
  - action: input_boolean.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: input_boolean.away_mode
  mode: single
- id: '1762257716179'
  alias: Gym Motion Light
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.gym_motion_sensor_occupancy
      no_motion_wait: 600
      light_target:
        area_id: gym
- id: '1764579321923'
  alias: Alert Aircon Filter Livingroom
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.living_room_filter_clean_required
    from:
    to:
    - 'on'
    for:
      hours: 0
      minutes: 5
      seconds: 0
  conditions: []
  actions:
  - action: notify.mobile_app_christians_iphone_2
    metadata: {}
    data:
      message: Clean Aircon filter
      title: "\U0001F3DA️ House Task:"
  mode: single
- id: '1765629245727'
  alias: Away mode On -> Ice Cube Maker Off
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - input_boolean.away_mode
    from:
    - 'off'
    to:
    - 'on'
  conditions: []
  actions:
  - action: switch.turn_off
    metadata: {}
    target:
      entity_id: switch.refrigerator_ice_maker
    data: {}
  mode: single
- id: '1765629437487'
  alias: Away Mode Off -> Ice Cube Maker On
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - input_boolean.away_mode
    to:
    - 'off'
  conditions: []
  actions:
  - action: switch.turn_on
    metadata: {}
    target:
      entity_id: switch.refrigerator_ice_maker
    data: {}
  mode: single
- id: '1769544929851'
  alias: Ikea_bilresa_scroll_wheel
  description: ''
  use_blueprint:
    path: jhol-byte/Ikea_bilresa_scroll_wheel.yaml
    input:
      remote: c5cf336be4126ec4ba7c83b13786fb48
      click_action_ch1:
      - action: light.toggle
        metadata: {}
        data: {}
        target:
          entity_id: light.kitchen_counter_lights
      scroll_wheel_target_ch1:
      - light.kitchen_counter_lights
      scroll_wheel_mode_ext_ch1: relaxed
- id: '1770135546260'
  alias: Scenic HVAC
  description: ''
  triggers:
  - trigger: webhook
    allowed_methods:
    - HEAD
    - GET
    local_only: false
    webhook_id: scenic-ac
  conditions: []
  actions:
  - action: renault.ac_start
    metadata: {}
    data:
      vehicle: b1c866f469a582c5ab78e186acf0cadc
      temperature: 21
  mode: single
- id: '1771747053961'
  alias: 'Alert: Car connected to Easee, update SOC'
  description: ''
  triggers:
  - type: plugged_in
    device_id: ed7235a0422718424e26846ade1fce2a
    entity_id: 7a737d08e718eacfd04cb0cf2d8f7e9c
    domain: binary_sensor
    trigger: device
  conditions: []
  actions:
  - action: notify.mobile_app_christians_iphone_2
    metadata: {}
    data:
      message: 'Current SOC: {{ states(''sensor.scenic_battery'') }} update Tibber!'
      title: "\U0001F699 Car connected:"
  mode: single
- id: '1772791565398'
  alias: House Calendar Alerts
  description: ''
  triggers:
  - trigger: calendar.event_started
    target:
      entity_id: calendar.house_tasks
    options:
      offset:
        hours: 0
        minutes: 0
        seconds: 0
        days: 0
      offset_type: before
  conditions: []
  actions:
  - action: notify.mobile_app_christians_iphone_2
    metadata: {}
    data:
      title: "\U0001F3DA️ House Task:"
      message: '{{ trigger.calendar_event.summary }}'
  mode: single
- id: '1772872632174'
  alias: Brann Match Start
  description: ''
  triggers:
  - trigger: calendar.event_started
    target:
      entity_id: calendar.terminliste_brann
    options:
      offset:
        hours: 0
        minutes: 5
        seconds: 0
        days: 0
      offset_type: before
  conditions: []
  actions:
  - action: light.turn_on
    metadata: {}
    target:
      entity_id: light.hallway
    data:
      rgb_color:
      - 209
      - 17
      - 28
      brightness_pct: 100
  - action: notify.mobile_app_christians_iphone_2
    metadata: {}
    data:
      title: '⚽️ Brann Match: {{ trigger.calendar_event.summary | default(''Calendar
        Event'') }}'
      message: '{{ trigger.calendar_event.description | default(''Calendar Event'')
        }}'
  mode: single
- id: '1772873063455'
  alias: 'Match Start: LFC'
  description: ''
  triggers:
  - trigger: calendar.event_started
    target:
      entity_id: calendar.liverpool
    options:
      offset:
        hours: 0
        minutes: 5
        seconds: 0
        days: 0
      offset_type: before
  conditions: []
  actions:
  - action: light.turn_on
    metadata: {}
    target:
      entity_id: light.hallway
    data:
      rgb_color:
      - 208
      - 0
      - 39
      brightness_pct: 100
  - action: notify.mobile_app_christians_iphone_2
    metadata: {}
    data:
      title: '⚽️ Liverpool Match: {{ trigger.calendar_event.summary | default(''Calendar
        Event'')  }}'
      message: '{{ trigger.calendar_event.description | default(''Calendar Event'')
        }}'
  mode: single
- id: '1772874499845'
  alias: "\U0001F697 Vehicle Charging Reminder"
  description: ''
  use_blueprint:
    path: stumiles86/VehicleChargingReminder.yaml
    input:
      battery_sensor: sensor.scenic_e_tech_state_of_charge
      vehicle_tracker: device_tracker.scenic_location
      charger_sensor: binary_sensor.easee_e_plug
      battery_threshold: 20
      notify_device: d6f5bb00c6bd80e6f8447e4fe02bf809
      reminder_time: '20:00:00'
