- id: '1624346947824'
  alias: Restore Samba Backup sensor on startup
  triggers:
  - event: start
    trigger: homeassistant
  actions:
  - data:
      addon: 15d21743_samba_backup
      input: restore-sensor
    action: hassio.addon_stdin
  mode: single
- id: '1674202038324'
  alias: Low battery level detection & notification for all battery sensors
  description: ''
  use_blueprint:
    path: sbyx/low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      actions:
      - service: notify.mobile_app_christians_iphone_2
        data:
          message: '{{sensors|replace(", ", "\n")}}'
          title: Low Battery Warning
      threshold: 10
      exclude:
        entity_id:
        - sensor.christians_iphone_2_battery_level
- id: '1679658995046'
  alias: Mount Synology
  description: ''
  triggers:
  - event: start
    trigger: homeassistant
  conditions: []
  actions:
  - data: {}
    action: shell_command.mount_syn_folder
  mode: single
- id: '1701207225668'
  alias: Cloud Lightning
  description: ''
  triggers:
  - allowed_methods:
    - POST
    - PUT
    local_only: true
    webhook_id: storm
    trigger: webhook
  conditions: []
  actions:
  - target:
      entity_id: []
      device_id:
      - f2253fe283ebeeb725aac76887945f22
      area_id: []
    data:
      effect: Lightning
      rgb_color:
      - 255
      - 255
      - 255
    action: light.turn_on
  mode: single
- id: '1701345981099'
  alias: Cloud Red
  description: ''
  triggers:
  - allowed_methods:
    - POST
    - PUT
    local_only: true
    webhook_id: cloud-red
    trigger: webhook
  conditions: []
  actions:
  - target:
      entity_id: []
      device_id:
      - f2253fe283ebeeb725aac76887945f22
      area_id: []
    data:
      rgb_color:
      - 255
      - 0
      - 0
      effect: Solid
    action: light.turn_on
  mode: single
- id: '1701346249652'
  alias: Cloud Blue
  description: ''
  triggers:
  - allowed_methods:
    - POST
    - PUT
    local_only: true
    webhook_id: cloud-blue
    trigger: webhook
  conditions: []
  actions:
  - target:
      entity_id: []
      device_id:
      - f2253fe283ebeeb725aac76887945f22
      area_id: []
    data:
      effect: Solid
      rgb_color:
      - 0
      - 76
      - 255
    action: light.turn_on
  mode: single
- id: '1701346601362'
  alias: Cloud White
  description: ''
  triggers:
  - allowed_methods:
    - POST
    - PUT
    local_only: true
    webhook_id: cloud-white
    trigger: webhook
  conditions: []
  actions:
  - target:
      entity_id: []
      device_id:
      - f2253fe283ebeeb725aac76887945f22
      area_id: []
    data:
      rgb_color:
      - 245
      - 245
      - 245
      effect: Solid
    action: light.toggle
  mode: single
- id: '1707217786984'
  alias: Update notifications
  description: ''
  use_blueprint:
    path: mdegat01/update_notifications.yaml
    input:
      mobile_app_device: d6f5bb00c6bd80e6f8447e4fe02bf809
      update_entities:
      - update.home_assistant_core_update
      - update.home_assistant_operating_system_update
      - update.home_assistant_supervisor_update
      mobile_app_device_2: d6f5bb00c6bd80e6f8447e4fe02bf809
      run_config_check: true
- id: '1716884266375'
  alias: Doorbell Video Livingroom Nest
  description: ''
  triggers:
  - entity_id:
    - input_button.doorbell_virtual_button
    trigger: state
  conditions: []
  actions:
  - metadata: {}
    data:
      media_player: media_player.travel_apple_tv
    target:
      entity_id: camera.aarlo_doorbell
    action: camera.play_stream
  mode: single
- id: '1718956792328'
  alias: UPS Unavailable Notification
  description: ''
  triggers:
  - entity_id:
    - sensor.ups_battery_charge_2
    from:
    to: unavailable
    for:
      hours: 0
      minutes: 1
      seconds: 0
    trigger: state
  conditions: []
  actions:
  - data:
      message: "UPS Offline again \U0001FAAB"
      title: UPS Event
    action: notify.mobile_app_christians_iphone_2
  mode: single
- id: '1718979526238'
  alias: UPS Online Notification
  description: ''
  triggers:
  - entity_id:
    - sensor.ups_status_2
    from: unavailable
    to:
    for:
      hours: 0
      minutes: 1
      seconds: 0
    trigger: state
  conditions: []
  actions:
  - data:
      message: "\U0001F50B UPS Online again "
      title: UPS Event
    action: notify.mobile_app_christians_iphone_2
  mode: single
- id: '1732448687057'
  alias: Gym Lights On/Off
  description: ''
  triggers:
  - domain: mqtt
    device_id: e60364c49ac435b7501e1dedc3414580
    type: action
    subtype: toggle
    trigger: device
  conditions: []
  actions:
  - type: toggle
    device_id: 4704fdcff0f46becf4831e763fbb69bf
    entity_id: 793e539428dec2eeb57e0f6604e635f1
    domain: light
  mode: single
- id: '1732448894365'
  alias: Gym Brightness Up
  description: ''
  triggers:
  - domain: mqtt
    device_id: e60364c49ac435b7501e1dedc3414580
    type: action
    subtype: brightness_up_click
    trigger: device
  conditions: []
  actions:
  - device_id: 4704fdcff0f46becf4831e763fbb69bf
    domain: light
    entity_id: 793e539428dec2eeb57e0f6604e635f1
    type: brightness_increase
  mode: single
- id: '1732448942273'
  alias: Gym Brightness Down
  description: ''
  triggers:
  - domain: mqtt
    device_id: e60364c49ac435b7501e1dedc3414580
    type: action
    subtype: brightness_down_click
    trigger: device
  conditions: []
  actions:
  - device_id: 4704fdcff0f46becf4831e763fbb69bf
    domain: light
    entity_id: 793e539428dec2eeb57e0f6604e635f1
    type: brightness_decrease
  mode: single
- id: '1733397222540'
  alias: Varmekabler Bad >30
  description: ''
  triggers:
  - type: temperature
    device_id: 15becaa5f6aa157b626aa79bf994ac28
    entity_id: cca94149328324f7953823c061b8d75c
    domain: sensor
    trigger: device
    above: 30
    for:
      hours: 0
      minutes: 0
      seconds: 0
  conditions: []
  actions:
  - action: notify.notify
    metadata: {}
    data:
      message: Varmekabler bad >30
  mode: single
- id: '1733397276363'
  alias: Varmekabler bad <22
  description: ''
  triggers:
  - type: temperature
    device_id: 15becaa5f6aa157b626aa79bf994ac28
    entity_id: cca94149328324f7953823c061b8d75c
    domain: sensor
    trigger: device
    for:
      hours: 0
      minutes: 0
      seconds: 0
    below: 22
  conditions: []
  actions:
  - action: notify.notify
    metadata: {}
    data:
      message: Varmekabler bad <22
  mode: single
- id: '1735805481133'
  alias: Tag Test is scanned
  description: ''
  triggers:
  - trigger: tag
    tag_id: f4bb661b-0974-4cf9-afa9-11c1a5ac98a8
  conditions: []
  actions:
  - action: notify.notify
    metadata: {}
    data:
      message: Tag scanned
  mode: single
- id: '1741349261358'
  alias: Aqara Button 1 Office Lights
  description: ''
  triggers:
  - domain: mqtt
    device_id: 84fa896a2a4671844bab358bbc3df444
    type: action
    subtype: single
    trigger: device
    id: aqara-button-1-single
  - domain: mqtt
    device_id: 84fa896a2a4671844bab358bbc3df444
    type: action
    subtype: double
    trigger: device
    id: aqara-button-1-double
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - aqara-button-1-single
      sequence:
      - action: light.toggle
        metadata: {}
        data: {}
        target:
          area_id: 55918db61e274c7898dd524589cff500
      - choose: []
    - conditions:
      - condition: trigger
        id:
        - aqara-button-1-double
      sequence:
      - action: light.turn_on
        metadata: {}
        data:
          brightness_pct: 100
        target:
          area_id: 55918db61e274c7898dd524589cff500
        enabled: false
      - action: light.toggle
        metadata: {}
        data:
          color_name: azure
          effect: Chase Flash Rnd
          brightness_pct: 30
        target:
          device_id: f2253fe283ebeeb725aac76887945f22
  mode: single
- id: '1744442641991'
  alias: Scenic
  description: ''
  triggers:
  - trigger: numeric_state
    entity_id:
    - sensor.scenic_mileage
    above: 7000
  conditions: []
  actions:
  - action: notify.mobile_app_christians_iphone_2
    metadata: {}
    data:
      title: Renault Scenic
      message: Mileage is {{ states('sensor.scenic_mileage') }} - Check insurance
        date 07.04.2025
  mode: single
- id: '1745064572661'
  alias: Remind to Set Starting Odometer
  description: Sends a reminder every April 7th to update the odometer starting value.
  triggers:
  - at: 09:00:00
    trigger: time
  conditions:
  - condition: template
    value_template: '{{ now().month == 4 and now().day == 7 }}'
  actions:
  - data:
      title: Update Car Odometer
      message: Don't forget to set the starting odometer for the new year!
      data:
        clickAction: /lovelace/car
    action: notify.mobile_app_christians_iphone_2
  mode: single
- id: '1745064660740'
  alias: Auto-set Starting Odometer on April 7
  description: Sets input_number.starting_odometer_april_7 from sensor.scenic_mileage
    every April 7 at 00:01.
  triggers:
  - at: 00:01:00
    trigger: time
  conditions:
  - condition: template
    value_template: '{{ now().month == 4 and now().day == 7 }}'
  actions:
  - data:
      entity_id: input_number.starting_odometer_april_7
      value: '{{ states(''sensor.scenic_mileage'') | float(0) }}

        '
    action: input_number.set_value
  mode: single
- id: '1745931966907'
  alias: Detect Easee->Car Connection - Start Charge Every 15min
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - sensor.easee_e_status
    to: awaiting_start
    from: disconnected
  conditions: []
  actions:
  - action: notify.mobile_app_christians_iphone_2
    metadata: {}
    data:
      message: Car connected to Easee-E
  - action: button.press
    metadata: {}
    data: {}
    target:
      entity_id: button.start_charge
  - repeat:
      sequence:
      - action: button.press
        metadata: {}
        data: {}
        target:
          device_id: b1c866f469a582c5ab78e186acf0cadc
      while:
      - condition: state
        entity_id: sensor.easee_e_status
        state: awaiting_start
  mode: single
- id: '1746096341274'
  alias: Cooktop on - Lights on
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - switch.cooktop_power
    from: 'off'
    to: 'on'
  conditions: []
  actions:
  - action: light.turn_on
    metadata: {}
    data: {}
    target:
      device_id:
      - c2df77741be7400dbd6e4483bdc60b57
      - 73a326af70cdcabb55111e83863debe8
  mode: single
