
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

frontend:
  themes: !include_dir_merge_named custom/themes

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

homeassistant:
  customize: !include customize.yaml
  latitude: 60.298089
  longitude: 5.340499

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

verisure:
  username: !secret verisure_username
  password: !secret verisure_password

sensor:
  - platform: version
  - platform: synology_dsm
    host: !secret synology_host
    username: !secret synology_username
    password: !secret synology_password
    monitored_conditions:
      - cpu_total_load
      - memory_real_usage
      - network_up
  
  - platform: tautulli
    api_key: !secret tautulli_api_key
    host: !secret tautulli_host

tibber:
  access_token: !secret tibber_access_token

media_player:
  - platform: volumio
    host: !secret volumio_host
    port: 3000

air_quality:
  - platform: norway_air
